<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-browserwasm;net10.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>SystemBackdropShowcase</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.systembackdropshowcase</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>SystemBackdropShowcase</ApplicationPublisher>
    <!-- Package Description -->
    <Description>SystemBackdropShowcase powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

</Project>
