trigger:
  branches:
    include:
      - master
      - feature/*

pr:
  branches:
    include:
      - master
      - feature/*

stages:
- stage: Determine_Changes
  displayName: Determine Changes
  jobs:
  - template: build/stage-determine-changes.yml

- stage: Docs_Validations
  displayName: Docs Validations
  dependsOn: Determine_Changes
  # Trigger this stage when docs files are changed
  condition: or(eq(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.docsOnly'], 'true'), eq(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.mixedChanges'], 'true'))
  jobs:
  - template: build/stage-docs-validations.yml

- stage: Build_Samples
  displayName: Build Samples
  dependsOn: Determine_Changes
  # Don't trigger this stage if only docs files are changed
  condition: ne(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.docsOnly'], 'true')
  jobs:
    - template: build/stage-build-samples.yml