steps:
- pwsh: |
    git merge origin/master -s recursive -X theirs
    $savedMSBuildExtensionsPath = $env:MSBuildExtensionsPath
    $env:MSBuildExtensionsPath = 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild'
    dotnet new sln --name=Uno.Samples.generated
    dotnet sln Uno.Samples.generated.sln add (Get-ChildItem -Recurse *.csproj)
    $env:MSBuildExtensionsPath = $savedMSBuildExtensionsPath

- task: nventiveCanaryUpdater@5
  inputs:
    solution: Uno.Samples.generated.sln
    usePrivateFeed: false
    useNuGetOrg: true
    mergeBranch: true
    nugetUpdaterVersion: '2.3.0-alpha.35'
    allowDowngrade: true
    packageAuthor: 'nventive,Uno Platform'
    summaryFile: '$(Build.ArtifactStagingDirectory)/Summary.md'
    resultFile: '$(Build.ArtifactStagingDirectory)/Results.json'

- pwsh: |
    del Uno.Samples.generated.sln