//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace LottieBuiltIn.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile sunrise.json
//       
//       Input file:
//           sunrise.json (9774 bytes created 20:13+02:00 Oct 10 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   102 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |    15 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     3 |
// | Animated gradient stops  |     3 |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     2 |
// | CompositionSpriteShapes  |    16 |
// |--------------------------+-------|
// | Brushes                  |     5 |
// | Gradient stops           |     3 |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace LottieBuiltIn.AnimatedVisuals
{
    // Name:        safe
    // Frame rate:  60 fps
    // Frame count: 120
    // Duration:    2000.0 mS
    sealed class Sunrise
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 2.000 seconds.
        internal const long c_durationTicks = 20000000;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new Sunrise_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 120d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(20000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 120d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Sunrise_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 20000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _animatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C;
            CompositionColorBrush _animatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838;
            CompositionColorBrush _animatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99;
            CompositionColorGradientStop _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F;
            CompositionColorGradientStop _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C;
            CompositionColorGradientStop _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionEllipseGeometry _ellipse_0;
            CompositionEllipseGeometry _ellipse_38;
            CompositionRoundedRectangleGeometry _roundedRectangle_5x12;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            Vector2KeyFrameAnimation _offsetVector2Animation;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ColorKeyFrameAnimation CreateColorKeyFrameAnimation(float initialProgress, Color initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InterpolationColorSpace = CompositionColorSpace.Rgb;
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: 
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0xFF, 0x8C, 0x4C), HoldThenStepEasingFunction());
                // Frame 60.
                // AlmostKhaki_FFFFE059
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0xFF, 0xE0, 0x59), CubicBezierEasingFunction_0());
                // Frame 120.
                // AlmostCoral_FFFF8C4C
                result.InsertKeyFrame(1F, Color.FromArgb(0xFF, 0xFF, 0x8C, 0x4C), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<100, 100>
            // Stop 1
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0x59, 0x3F, 0x7F), HoldThenStepEasingFunction());
                // Frame 60.
                // AlmostLightSalmon_FFF9A57F
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0xF9, 0xA5, 0x7F), CubicBezierEasingFunction_0());
                // Frame 120.
                // AlmostDarkSlateBlue_FF593F7F
                result.InsertKeyFrame(1F, Color.FromArgb(0xFF, 0x59, 0x3F, 0x7F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // -  Offset:<100, 150>
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0x19, 0x28, 0x38), HoldThenStepEasingFunction());
                // Frame 60.
                // AlmostDarkSlateGray_FF284C4C
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0x28, 0x4C, 0x4C), CubicBezierEasingFunction_0());
                // Frame 120.
                // AlmostDarkSlateGray_FF192838
                result.InsertKeyFrame(1F, Color.FromArgb(0xFF, 0x19, 0x28, 0x38), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<100, 100>
            // Stop 0
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0x19, 0x1E, 0x4C), HoldThenStepEasingFunction());
                // Frame 60.
                // AlmostRoyalBlue_FF4C7FD8
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0x4C, 0x7F, 0xD8), CubicBezierEasingFunction_0());
                // Frame 120.
                // AlmostMidnightBlue_FF191E4C
                result.InsertKeyFrame(1F, Color.FromArgb(0xFF, 0x19, 0x1E, 0x4C), CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<100, 100>
            // Stop 2
            // Color
            ColorKeyFrameAnimation ColorAnimation_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0xFF, 0xF2, 0x8C, 0x72), HoldThenStepEasingFunction());
                // Frame 60.
                // AlmostKhaki_FFFFD872
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0xFF, 0xD8, 0x72), CubicBezierEasingFunction_0());
                // Frame 120.
                // AlmostSalmon_FFF28C72
                result.InsertKeyFrame(1F, Color.FromArgb(0xFF, 0xF2, 0x8C, 0x72), CubicBezierEasingFunction_0());
                return result;
            }

            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xFF, 0xEA, 0x99), HoldThenStepEasingFunction());
                // Frame 60.
                // AlmostKhaki_FFFFEA99
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0xFF, 0xEA, 0x99), CubicBezierEasingFunction_0());
                // Frame 120.
                // TransparentAlmostKhaki_00FFEA99
                result.InsertKeyFrame(1F, Color.FromArgb(0x00, 0xFF, 0xEA, 0x99), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup:
            CompositionColorBrush AnimatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C()
            {
                if (_animatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C != null) { return _animatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C; }
                var result = _animatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C = _c.CreateColorBrush();
                return result;
            }

            // - Layer aggregator
            // Offset:<100, 150>
            CompositionColorBrush AnimatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838()
            {
                if (_animatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838 != null) { return _animatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838; }
                var result = _animatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838 = _c.CreateColorBrush();
                return result;
            }

            CompositionColorBrush AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99()
            {
                if (_animatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99 != null) { return _animatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99; }
                var result = _animatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99 = _c.CreateColorBrush();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup:
            CompositionColorBrush ColorBrush_SemiTransparentAlmostKhaki_B2FFE57F()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xB2, 0xFF, 0xE5, 0x7F));
            }

            // - - Layer aggregator
            // -  Offset:<100, 100>
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F()
            {
                if (_animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F != null) { return _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F; }
                var result = _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - Layer aggregator
            // -  Offset:<100, 100>
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C()
            {
                if (_animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C != null) { return _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C; }
                var result = _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - Layer aggregator
            // -  Offset:<100, 100>
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72()
            {
                if (_animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72 != null) { return _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72; }
                var result = _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup:
                shapes.Add(SpriteShape_01());
                // ShapeGroup:
                shapes.Add(SpriteShape_02());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // ShapeGroup:  RotationDegrees:330
                shapes.Add(SpriteShape_03());
                // ShapeGroup:  RotationDegrees:300
                shapes.Add(SpriteShape_04());
                // ShapeGroup:  RotationDegrees:270
                shapes.Add(SpriteShape_05());
                // ShapeGroup:  RotationDegrees:240
                shapes.Add(SpriteShape_06());
                // ShapeGroup:  RotationDegrees:210
                shapes.Add(SpriteShape_07());
                // ShapeGroup:  RotationDegrees:180
                shapes.Add(SpriteShape_08());
                // ShapeGroup:  RotationDegrees:150
                shapes.Add(SpriteShape_09());
                // ShapeGroup:  RotationDegrees:120
                shapes.Add(SpriteShape_10());
                // ShapeGroup:  RotationDegrees:90
                shapes.Add(SpriteShape_11());
                // ShapeGroup:  RotationDegrees:60
                shapes.Add(SpriteShape_12());
                // ShapeGroup:  RotationDegrees:30
                shapes.Add(SpriteShape_13());
                // ShapeGroup:
                shapes.Add(SpriteShape_14());
                return result;
            }

            // - Layer aggregator
            // Offset:<100, 150>
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_0()
            {
                if (_ellipse_0 != null) { return _ellipse_0; }
                var result = _ellipse_0 = _c.CreateEllipseGeometry();
                result.Center = new Vector2(0F, 90F);
                result.Radius = new Vector2(0F, 0F);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: 
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_28()
            {
                var result = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(28F, 28F);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: 
            // .EllipseGeometry
            CompositionEllipseGeometry Ellipse_38()
            {
                if (_ellipse_38 != null) { return _ellipse_38; }
                var result = _ellipse_38 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(38F, 38F);
                return result;
            }

            // - Layer aggregator
            // Offset:<100, 100>
            CompositionLinearGradientBrush LinearGradientBrush()
            {
                var result = _c.CreateLinearGradientBrush();
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C());
                colorStops.Add(AnimatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F());
                colorStops.Add(AnimatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(100F, 0F);
                result.EndPoint = new Vector2(100F, 200F);
                return result;
            }

            // - Layer aggregator
            // Offset:<100, 100>
            // .RectangleGeometry
            CompositionRectangleGeometry Rectangle_200()
            {
                var result = _c.CreateRectangleGeometry();
                result.Offset = new Vector2(-100F, -100F);
                result.Size = new Vector2(200F, 200F);
                return result;
            }

            // .RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_5x12()
            {
                if (_roundedRectangle_5x12 != null) { return _roundedRectangle_5x12; }
                var result = _roundedRectangle_5x12 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(2.5F, 2.5F);
                result.Offset = new Vector2(-2.5F, -58F);
                result.Size = new Vector2(5F, 12F);
                return result;
            }

            // Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<100, 100>
                var geometry = Rectangle_200();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 100F, 100F), LinearGradientBrush());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape(Ellipse_38());
                result.StrokeBrush = ColorBrush_SemiTransparentAlmostKhaki_B2FFE57F();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeThickness = 4F;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape(Ellipse_28());
                result.FillBrush = AnimatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C();
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:330
            CompositionSpriteShape SpriteShape_03()
            {
                // Rotation:-30.0000193141719 degrees, Scale:<0.99999994, 0.99999994>
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.866025209F, -0.500000298F, 0.500000298F, 0.866025209F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:300
            CompositionSpriteShape SpriteShape_04()
            {
                // Rotation:-60.00001577364497 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.499999762F, -0.866025567F, 0.866025567F, 0.499999762F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:270
            CompositionSpriteShape SpriteShape_05()
            {
                // Rotation:-90 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0F, -1F, 1F, 0F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:240
            CompositionSpriteShape SpriteShape_06()
            {
                // Rotation:-120.00000394341166 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(-0.50000006F, -0.866025388F, 0.866025388F, -0.50000006F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:210
            CompositionSpriteShape SpriteShape_07()
            {
                // Rotation:-150.00001187921234 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(-0.866025507F, -0.499999821F, 0.499999821F, -0.866025507F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:180
            CompositionSpriteShape SpriteShape_08()
            {
                // Rotation:-180 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(-1F, 0F, -0F, -1F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:150
            CompositionSpriteShape SpriteShape_09()
            {
                // Rotation:149.9999982188319 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(-0.866025388F, 0.50000006F, -0.50000006F, -0.866025388F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:120
            CompositionSpriteShape SpriteShape_10()
            {
                // Rotation:120.00000394341166 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(-0.50000006F, 0.866025388F, -0.866025388F, -0.50000006F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:90
            CompositionSpriteShape SpriteShape_11()
            {
                // Rotation:90 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0F, 1F, -1F, 0F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:60
            CompositionSpriteShape SpriteShape_12()
            {
                // Rotation:60.000001971705764 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.49999997F, 0.866025448F, -0.866025448F, 0.49999997F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:  RotationDegrees:30
            CompositionSpriteShape SpriteShape_13()
            {
                // Rotation:30.000001781168113 degrees
                var geometry = RoundedRectangle_5x12();
                var result = CreateSpriteShape(geometry, new Matrix3x2(0.866025388F, 0.5F, -0.5F, 0.866025388F, 0F, 0F), AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99());;
                return result;
            }

            // - Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_14()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_5x12());
                result.FillBrush = AnimatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99();
                return result;
            }

            // Layer aggregator
            // ShapeGroup:
            CompositionSpriteShape SpriteShape_15()
            {
                // Offset:<100, 150>
                var geometry = Ellipse_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 100F, 150F), AnimatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.600000024F, 0F), new Vector2(0.400000006F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - - Layer aggregator
            // - -  Offset:<100, 100>
            // Stop 0
            // Offset
            ScalarKeyFrameAnimation OffsetScalarAnimation_0_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, 0F, CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<100, 100>
            // Stop 1
            // Offset
            ScalarKeyFrameAnimation OffsetScalarAnimation_0p55_to_0p55()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0.550000012F, HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, 0.550000012F, CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, 0.550000012F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<100, 100>
            // Stop 2
            // Offset
            ScalarKeyFrameAnimation OffsetScalarAnimation_1_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 1F, HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, 1F, CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_90()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 120.
                result.InsertKeyFrame(1F, 90F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: 
            // .EllipseGeometry
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0p005_to_0p005()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0.00499999989F, HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, 1F, CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, 0.00499999989F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(200F, 200F);
                var shapes = result.Shapes;
                // Offset:<100, 100>
                shapes.Add(SpriteShape_00());
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                // Offset:<100, 150>
                shapes.Add(SpriteShape_15());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                if (_offsetVector2Animation != null) { return _offsetVector2Animation; }
                var result = _offsetVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(100F, 150F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(100F, 92F), CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector2(100F, 150F), CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // -  Offset:<100, 150>
            // .EllipseGeometry
            // Radius
            Vector2KeyFrameAnimation RadiusVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(210F, 75F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(180F, 95F), CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector2(210F, 75F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), HoldThenStepEasingFunction());
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(1.10000002F, 1.10000002F), CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                return result;
            }

            internal Sunrise_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(200F, 200F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _animatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C.StartAnimation("Color", ColorAnimation_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C(), AnimationController_0());
                _animatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838.StartAnimation("Color", ColorAnimation_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838(), AnimationController_0());
                _animatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99.StartAnimation("Color", ColorAnimation_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99(), AnimationController_0());
                _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F.StartAnimation("Color", ColorAnimation_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F(), AnimationController_0());
                _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F.StartAnimation("Offset", OffsetScalarAnimation_0p55_to_0p55(), AnimationController_0());
                _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C.StartAnimation("Color", ColorAnimation_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C(), AnimationController_0());
                _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C.StartAnimation("Offset", OffsetScalarAnimation_0_to_0(), AnimationController_0());
                _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72.StartAnimation("Color", ColorAnimation_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72(), AnimationController_0());
                _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72.StartAnimation("Offset", OffsetScalarAnimation_1_to_1(), AnimationController_0());
                _containerShape_0.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
                _containerShape_0.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
                _containerShape_1.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_90(), AnimationController_0());
                _containerShape_1.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
                _ellipse_0.StartAnimation("Radius", RadiusVector2Animation(), AnimationController_0());
                _ellipse_38.StartAnimation("TrimEnd", TrimEndScalarAnimation_0p005_to_0p005(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _animatedColorBrush_AlmostCoral_FFFF8C4C_to_AlmostCoral_FFFF8C4C.StopAnimation("Color");
                _animatedColorBrush_AlmostDarkSlateGray_FF192838_to_AlmostDarkSlateGray_FF192838.StopAnimation("Color");
                _animatedColorBrush_TransparentAlmostKhaki_00FFEA99_to_TransparentAlmostKhaki_00FFEA99.StopAnimation("Color");
                _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F.StopAnimation("Color");
                _animatedGradientStop_0_AlmostDarkSlateBlue_FF593F7F_to_AlmostDarkSlateBlue_FF593F7F.StopAnimation("Offset");
                _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C.StopAnimation("Color");
                _animatedGradientStop_0_AlmostMidnightBlue_FF191E4C_to_AlmostMidnightBlue_FF191E4C.StopAnimation("Offset");
                _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72.StopAnimation("Color");
                _animatedGradientStop_0_AlmostSalmon_FFF28C72_to_AlmostSalmon_FFF28C72.StopAnimation("Offset");
                _containerShape_0.StopAnimation("Scale");
                _containerShape_0.StopAnimation("Offset");
                _containerShape_1.StopAnimation("RotationAngleInDegrees");
                _containerShape_1.StopAnimation("Offset");
                _ellipse_0.StopAnimation("Radius");
                _ellipse_38.StopAnimation("TrimEnd");
            }

        }
    }
}
