global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoPongWars.Models;
global using UnoPongWars.Presentation;
global using UnoPongWars.DataContracts;
global using UnoPongWars.DataContracts.Serialization;
global using UnoPongWars.Services.Caching;
global using UnoPongWars.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using Color = Windows.UI.Color;
global using UnoPongWars.Business.Models;
