-- Penguins sample app — one-time backend setup.
-- Paste into a NEW Supabase project: Dashboard → SQL Editor → New query → Run.
-- Creates the schema, Row-Level Security policies, and fictional seed data
-- (safe to ship — no real personal data). Dates are relative to the run date
-- so the schedule stays sensible whenever you seed.

-- ─────────────────────────────────────────────────────────────────────────
-- Schema
-- ─────────────────────────────────────────────────────────────────────────

create table if not exists players (
    id          int generated by default as identity primary key,
    name        text    not null,
    number      int     not null,
    position    text    not null default '',
    is_injured  boolean not null default false,
    created_at  timestamptz not null default now()
);

create table if not exists games (
    id          int generated by default as identity primary key,
    opponent    text    not null,
    game_date   date    not null,
    game_time   text    not null default '21:15',
    rink        text    not null default '',
    home_score  int,
    away_score  int,
    is_home     boolean not null default true,
    created_at  timestamptz not null default now()
);

create table if not exists attendance (
    id          int generated by default as identity primary key,
    player_id   int  not null references players(id) on delete cascade,
    week_of     date not null,
    status      text not null default 'pending' check (status in ('in','out','pending')),
    updated_at  timestamptz not null default now(),
    unique (player_id, week_of)
);

create table if not exists chat_messages (
    id          int generated by default as identity primary key,
    player_id   int  references players(id) on delete set null,
    player_name text not null default '',
    message     text not null,
    created_at  timestamptz not null default now()
);

create table if not exists beer_tracker (
    id             int generated by default as identity primary key,
    season         text not null,
    consumed_cases int  not null default 0,
    updated_at     timestamptz not null default now(),
    unique (season)
);

create table if not exists duties (
    id         int generated by default as identity primary key,
    game_id    int not null references games(id) on delete cascade,
    player_id  int references players(id) on delete set null,
    duty_type  text not null,
    created_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────
-- Row-Level Security (the real security boundary; the app uses the anon role)
-- ─────────────────────────────────────────────────────────────────────────

alter table players       enable row level security;
alter table games         enable row level security;
alter table attendance    enable row level security;
alter table chat_messages enable row level security;
alter table beer_tracker  enable row level security;
alter table duties        enable row level security;

create policy "read players" on players for select to anon using (true);
create policy "read games"   on games   for select to anon using (true);

create policy "read attendance"   on attendance for select to anon using (true);
create policy "insert attendance" on attendance for insert to anon with check (true);
create policy "update attendance" on attendance for update to anon using (true) with check (true);

create policy "read chat"   on chat_messages for select to anon using (true);
create policy "insert chat" on chat_messages for insert to anon with check (true);

create policy "read beer"   on beer_tracker for select to anon using (true);
create policy "update beer" on beer_tracker for update to anon using (true) with check (true);

create policy "read duties"   on duties for select to anon using (true);
create policy "insert duties" on duties for insert to anon with check (true);
create policy "delete duties" on duties for delete to anon using (true);

-- ─────────────────────────────────────────────────────────────────────────
-- Seed data (fictional)
-- ─────────────────────────────────────────────────────────────────────────

insert into players (id, name, number, position, is_injured) values
    (1,  'Marc Tremblay',    7,  'C',  false),
    (2,  'Patrick Bouchard', 11, 'LW', false),
    (3,  'Steve Lapointe',   14, 'RW', false),
    (4,  'Jean-Luc Martin',  19, 'C',  false),
    (5,  'Mike Gagnon',      22, 'D',  false),
    (6,  'Dave Caron',       24, 'D',  false),
    (7,  'Phil Bergeron',    27, 'LW', false),
    (8,  'Eric Pelletier',   31, 'G',  false),
    (9,  'Ryan Dubois',      33, 'RW', false),
    (10, 'Luc Belanger',     37, 'D',  true),
    (11, 'Kevin Roy',        41, 'C',  false),
    (12, 'Dan Fournier',     44, 'LW', false),
    (13, 'Chris Levesque',   55, 'D',  false),
    (14, 'Alex Nadeau',      61, 'RW', false),
    (15, 'Ben Gauthier',     77, 'G',  false);

-- The app defaults to season '2024-2025' (ISupabaseService.GetBeerTrackerAsync).
insert into beer_tracker (season, consumed_cases) values ('2024-2025', 17);

-- Past games (with scores) and upcoming games, relative to today.
insert into games (opponent, game_date, game_time, rink, home_score, away_score, is_home) values
    ('Beaconsfield Bears',   current_date - 21, '21:15', 'Dorval Arena',     6, 3, true),
    ('Kirkland Kings',       current_date - 14, '21:15', 'Kirkland Arena',   2, 5, false),
    ('DDO Storm',            current_date - 7,  '21:15', 'Dorval Arena',     7, 4, true),
    ('Lachine Hawks',        current_date + 4,  '21:15', 'Dorval Arena',     null, null, true),
    ('Pointe-Claire Blades', current_date + 11, '21:15', 'Pointe-Claire Aquatic Centre', null, null, false),
    ('St-Lazare Wolves',     current_date + 18, '21:15', 'Dorval Arena',     null, null, true);

-- Attendance for the current week (Monday-anchored).
insert into attendance (player_id, week_of, status)
select id,
       date_trunc('week', current_date)::date,
       (array['in','in','in','in','in','in','in','in','out','out','pending','pending','in','in','in'])[id]
from players;

insert into chat_messages (player_id, player_name, message, created_at) values
    (1,  'Marc Tremblay',  'Who''s bringing beer this week?',            now() - interval '48 hours'),
    (7,  'Phil Bergeron',  'I got it. Grabbing two flats of Molson Ex.', now() - interval '47 hours'),
    (5,  'Mike Gagnon',    'Beauty. I''ll bring the cooler.',            now() - interval '46 hours'),
    (10, 'Luc Belanger',   'Still sore. Gonna sit this one out boys.',   now() - interval '29 hours'),
    (11, 'Kevin Roy',      'Let''s go boys! Bounce back from last week.', now() - interval '12 hours'),
    (1,  'Marc Tremblay',  'Mark yourselves in or out — need a headcount.', now() - interval '2 hours');

-- Duties for the next upcoming game.
insert into duties (game_id, player_id, duty_type)
select g.id, v.player_id, v.duty_type
from (select id from games where game_date >= current_date order by game_date limit 1) g
cross join (values (9,'ice'), (7,'beer'), (5,'cooler'), (12,'food')) as v(player_id, duty_type);

-- Keep identity sequences ahead of the explicit ids inserted above.
select setval(pg_get_serial_sequence('players','id'), (select max(id) from players));
