global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using MVUX.Models;
global using MVUX.Presentation;
global using MVUX.DataContracts;
global using MVUX.DataContracts.Serialization;
global using MVUX.Services.Caching;
global using MVUX.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
